# -*- coding: utf-8 -*-
grist_data = {
	 'Wheat Flour': {'EBC': 0.0, 'Type': 3.0, 'Extract': 304.0, 'Description': 'No Description', 'Moisture': 11.0, 'Fermentability': 200.0},
	 'Flaked Barley': {'EBC': 0.0, 'Type': 3.0, 'Extract': 253.0, 'Description': 'No Description', 'Moisture': 9.0, 'Fermentability': 200.0},
	 'Sugar Invert No. 1 Solid': {'EBC': 30.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Barley Syrup': {'EBC': 0.0, 'Type': 5.0, 'Extract': 279.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 62.0},
	 'Malt Extract Syrup Medium': {'EBC': 10.0, 'Type': 5.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 63.0},
	 'Sugar Invert No.2 Syrup': {'EBC': 65.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Extra Pale Malt': {'EBC': 2.5, 'Type': 1.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Sugar Invert No.1 Syrup': {'EBC': 30.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Sugar Invert No.4 Syrup': {'EBC': 600.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Torrefied Wheat': {'EBC': 4.0, 'Type': 3.0, 'Extract': 273.0, 'Description': 'No Description', 'Moisture': 6.0, 'Fermentability': 200.0},
	 'Caragold': {'EBC': 9.0, 'Type': 4.0, 'Extract': 298.0, 'Description': 'No Description', 'Moisture': 7.5, 'Fermentability': 50.0},
	 'Oat Malt': {'EBC': 3.5, 'Type': 1.0, 'Extract': 255.0, 'Description': 'No Description', 'Moisture': 4.0, 'Fermentability': 200.0},
	 'Roasted Barley': {'EBC': 1350.0, 'Type': 4.0, 'Extract': 260.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 0.0},
	 'Pilsener Malt': {'EBC': 2.5, 'Type': 1.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 4.5, 'Fermentability': 200.0},
	 'Pale Amber Malt': {'EBC': 30.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 200.0},
	 'Crystal Malt, Pale': {'EBC': 60.0, 'Type': 4.0, 'Extract': 260.0, 'Description': 'No Description', 'Moisture': 7.0, 'Fermentability': 50.0},
	 'Lager Malt': {'EBC': 2.5, 'Type': 1.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 4.5, 'Fermentability': 200.0},
	 'Mild Ale Malt': {'EBC': 6.0, 'Type': 1.0, 'Extract': 292.0, 'Description': 'No Description', 'Moisture': 2.8, 'Fermentability': 200.0},
	 'Black Malt': {'EBC': 1300.0, 'Type': 4.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 0.0},
	 'Dextrose Monohydrate': {'EBC': 0.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 200.0},
	 'Dried Malt Extract Dark': {'EBC': 60.0, 'Type': 5.0, 'Extract': 350.0, 'Description': 'No Description', 'Moisture': 5.5, 'Fermentability': 63.0},
	 'Malto-Dextrin': {'EBC': 0.0, 'Type': 6.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 35.0},
	 'Munich Malt': {'EBC': 20.0, 'Type': 1.0, 'Extract': 296.0, 'Description': 'No Description', 'Moisture': 2.2, 'Fermentability': 200.0},
	 'Flaked Wheat': {'EBC': 0.0, 'Type': 3.0, 'Extract': 279.0, 'Description': 'No Description', 'Moisture': 8.0, 'Fermentability': 200.0},
	 'Dried Malt Ext. Xtra Pale': {'EBC': 5.5, 'Type': 5.0, 'Extract': 350.0, 'Description': 'No Description', 'Moisture': 5.5, 'Fermentability': 63.0},
	 'Flaked Maize': {'EBC': 0.0, 'Type': 3.0, 'Extract': 313.0, 'Description': 'No Description', 'Moisture': 9.0, 'Fermentability': 200.0},
	 'Torrefied Barley': {'EBC': 0.0, 'Type': 3.0, 'Extract': 253.0, 'Description': 'No Description', 'Moisture': 5.0, 'Fermentability': 200.0},
	 'Brown Malt': {'EBC': 150.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 200.0},
	 'Chocolate Wheat Malt': {'EBC': 800.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 15.0},
	 'Sugar, Demerara': {'EBC': 50.0, 'Type': 6.0, 'Extract': 370.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Sugar Invert No. 4 Solid': {'EBC': 600.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Crystal Malt': {'EBC': 130.0, 'Type': 4.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 4.5, 'Fermentability': 50.0},
	 'Pinhead Oats': {'EBC': 2.5, 'Type': 3.0, 'Extract': 260.0, 'Description': 'No Description', 'Moisture': 8.0, 'Fermentability': 200.0},
	 'Sugar Invert No.3 Syrup': {'EBC': 130.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Dried Malt Extract Medium': {'EBC': 35.0, 'Type': 5.0, 'Extract': 350.0, 'Description': 'No Description', 'Moisture': 5.5, 'Fermentability': 63.0},
	 'Sugar Invert No. 2 Solid': {'EBC': 65.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Maris Otter, Low Colour': {'EBC': 2.5, 'Type': 1.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Malt Extract Syrup Pale': {'EBC': 5.5, 'Type': 5.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 63.0},
	 'Flaked Oats': {'EBC': 0.0, 'Type': 3.0, 'Extract': 160.0, 'Description': 'No Description', 'Moisture': 9.0, 'Fermentability': 200.0},
	 'Dried Malt Ext. Wheat': {'EBC': 5.5, 'Type': 5.0, 'Extract': 350.0, 'Description': 'No Description', 'Moisture': 5.5, 'Fermentability': 63.0},
	 'Vienna Malt': {'EBC': 7.5, 'Type': 1.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Imperial Malt': {'EBC': 50.0, 'Type': 2.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Wheat Malt': {'EBC': 3.5, 'Type': 1.0, 'Extract': 279.0, 'Description': 'No Description', 'Moisture': 4.0, 'Fermentability': 200.0},
	 'Rice': {'EBC': 0.0, 'Type': 3.0, 'Extract': 323.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 200.0},
	 'Rye Malt': {'EBC': 6.0, 'Type': 2.0, 'Extract': 242.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 200.0},
	 'Chocolate Malt Low Colour': {'EBC': 500.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 15.0},
	 'Dried Malt Extract Pale': {'EBC': 10.0, 'Type': 5.0, 'Extract': 350.0, 'Description': 'No Description', 'Moisture': 5.5, 'Fermentability': 63.0},
	 'Oat Flakes': {'EBC': 2.5, 'Type': 3.0, 'Extract': 260.0, 'Description': 'No Description', 'Moisture': 8.0, 'Fermentability': 200.0},
	 'Maris Otter': {'EBC': 5.0, 'Type': 1.0, 'Extract': 296.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Chocolate Malt': {'EBC': 1050.0, 'Type': 4.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 15.0},
	 'Pale Malt': {'EBC': 5.0, 'Type': 1.0, 'Extract': 296.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Caramalt': {'EBC': 30.0, 'Type': 4.0, 'Extract': 255.0, 'Description': 'No Description', 'Moisture': 7.5, 'Fermentability': 50.0},
	 'Crystal Malt, Dark': {'EBC': 300.0, 'Type': 4.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 4.5, 'Fermentability': 50.0},
	 'Sugar, Household White': {'EBC': 0.0, 'Type': 6.0, 'Extract': 375.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Amber Malt': {'EBC': 60.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 200.0},
	 'Malt Extract Syrup Amber': {'EBC': 18.0, 'Type': 5.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 63.0},
	 'Malt Extract Syrup Dark': {'EBC': 55.0, 'Type': 5.0, 'Extract': 300.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 63.0},
	 'Sugar Invert No. 3 Solid': {'EBC': 130.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Honey': {'EBC': 0.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Wheat Malt Extract': {'EBC': 8.0, 'Type': 5.0, 'Extract': 309.0, 'Description': 'Usually an extract made from 55% Wheat malt + 45% barley malt.', 'Moisture': 0.0, 'Fermentability': 63.0},
	 'Caramel': {'EBC': 950.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Dark Amber Malt': {'EBC': 100.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 200.0},
	 'Dried Beans': {'EBC': 5.0, 'Type': 1.0, 'Extract': 271.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Dried Peas': {'EBC': 5.0, 'Type': 1.0, 'Extract': 271.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Elderberry Dried': {'EBC': 100.0, 'Type': 2.0, 'Extract': 265.0, 'Description': 'No Description', 'Moisture': 3.0, 'Fermentability': 30.0},
	 'Glucose (Dex Monohydrate)': {'EBC': 0.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 200.0},
	 'Golden Promise': {'EBC': 4.5, 'Type': 1.0, 'Extract': 296.0, 'Description': 'No Description', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Golden Syrup': {'EBC': 30.0, 'Type': 6.0, 'Extract': 319.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Lactose': {'EBC': 0.0, 'Type': 6.0, 'Extract': 375.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 0.0},
	 'Molasses': {'EBC': 950.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 40.0},
	 'Pumpkin': {'EBC': 10.0, 'Type': 3.0, 'Extract': 25.0, 'Description': 'Guess', 'Moisture': 3.5, 'Fermentability': 200.0},
	 'Sugar, Muscovado': {'EBC': 600.0, 'Type': 6.0, 'Extract': 370.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 100.0},
	 'Treacle': {'EBC': 950.0, 'Type': 6.0, 'Extract': 360.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 50.0}
}



hop_data = {
	 'Nelson Sauvin': {'Form': 'Whole', 'Origin': 'New Zeland', 'Alpha': 12.7, 'Use': 'General Purpose', 'Description': 'No Description'},
	 'Pilot': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 11.5, 'Use': 'Aroma', 'Description': 'Very new high-alpha variety'},
	 'Columbus (Tomahawk)': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 15.0, 'Use': 'Bittering', 'Description': 'Very high alpha used mainly in copper but also good aroma if used late'},
	 'Admiral': {'Form': 'Whole', 'Origin': 'British', 'Alpha': 14.4, 'Use': 'Bittering', 'Description': 'No Description'},
	 'Boadicea': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 7.9, 'Use': 'General Purpose', 'Description': 'Waiting'},
	 'Pilgrim': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 11.6, 'Use': 'Bittering', 'Description': 'A new high-alpha copper hop, useful as a substitute for Target and Challenger. Much hoppier aroma than Target.'},
	 'Crystal': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 4.5, 'Use': 'Aroma', 'Description': 'Aroma hop with delicate flavour and hints of tangerine.'},
	 'Green Bullet': {'Form': 'Whole', 'Origin': 'New Zealand', 'Alpha': 13.9, 'Use': 'General Purpose', 'Description': 'High alpha hop, but suitable for late and dry hopping. Likened to a Styrian in flavour with pine lemon crispness and excellent aroma.'},
	 'Northdown': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 8.3, 'Use': 'General Purpose', 'Description': 'A versatile general-purpose hop with good bitterness and aroma properties. Has Challenger-type chsaracteristics but richer flavour.'},
	 'Citra': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 13.0, 'Use': 'General Purpose', 'Description': 'Distinctive aromatic with moderate bittering.'},
	 'Cascade': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 5.7, 'Use': 'Aroma', 'Description': 'An American variety with a very floral/ spicy aroma with good bittering quality. Typical American flavour which some may find objectional.'},
	 'Jeanette': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 6.0, 'Use': 'Aroma', 'Description': 'Delicate, clean and refreshing, slightly floral'},
	 'Willamette': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 4.7, 'Use': 'Aroma', 'Description': 'A Fuggle variety grown in America. Delicate estery/ blackcurrant/ herbal aroma. Not really a Fuggle replacement.'},
	 'Joan': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 9.8, 'Use': 'Aroma', 'Description': 'Powerful and fruity lovely citrus notes with a hint of liquorice. Naturally seedless'},
	 'Saaz': {'Form': 'Whole', 'Origin': 'Czech', 'Alpha': 3.3, 'Use': 'Aroma', 'Description': 'Traditional aroma variety for lager; earthy hop flavour. Used in Budvar Budweiser'},
	 'Nugget': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 13.0, 'Use': 'Bittering', 'Description': 'High alpha with good aroma'},
	 'Target': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 11.4, 'Use': 'Bittering', 'Description': 'High alpha, economical copper hop. Flavour is too harsh for late hopping.'},
	 'Challenger': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 7.6, 'Use': 'General Purpose', 'Description': 'A versatile general-purpose hop with good alpha and reasonable aroma properties, making it useful for both copper hopping and late hopping.  Provides a full-bodied rounded bitterness in copper, and with crisp fruity straw-like character as a late hop.'},
	 'Mount Hood': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 6.5, 'Use': 'Aroma', 'Description': 'Similar to Hallertau giving delicate, floral and slight herbal character'},
	 'Pioneer': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 9.0, 'Use': 'Aroma', 'Description': 'Unusual pleasant lemon/ grapefruit citrus aroma distinctively hoppy.'},
	 'Simcoe': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 13.0, 'Use': 'General Purpose', 'Description': 'Distinctive aromatic with moderate bittering.'},
	 'Pina': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 10.0, 'Use': 'Aroma', 'Description': 'Traditional WGV type with hints of lavender. Very low co-humulone.'},
	 'Hilary': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 9.75, 'Use': 'Bittering', 'Description': 'English dwarf hedgerow hop. Robust, full and rounded with refreshing spicy aroma'},
	 'Amarillo': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 9.5, 'Use': 'Aroma', 'Description': 'Unique very floral/ spicy. Powerful aroma with good bittering quality.'},
	 'Pacific Hallertau': {'Form': 'Whole', 'Origin': 'New Zealand', 'Alpha': 5.9, 'Use': 'Aroma', 'Description': 'Bred from Mittlefruh and has a typical Mittlefruh aroma combined with a smooth bouquet and mild buttery flavour notes.'},
	 'Hallertauer Mittlefruh': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 4.3, 'Use': 'Aroma', 'Description': 'Traditional lager aroma hop, with a delicate aroma.'},
	 'Northern Brewer': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 8.2, 'Use': 'General Purpose', 'Description': 'Dual purpose similar to Northdown with excellent bittering properties and a pleasant aroma.'},
	 'Warrior': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 8.0, 'Use': 'Bittering', 'Description': 'No Description'},
	 'Fuggle': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 4.9, 'Use': 'Aroma', 'Description': 'English Fuggle is a traditional hop; one of the most famous hops in the world which, along with Golding, made English ales famous. Delicate, minty, grassy slightly floral aroma. Traditionally used with Golding to provide a fully rounded flavour.'},
	 'Bramling Cross': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 6.3, 'Use': 'Aroma', 'Description': u"A Golding cross with a distinctive 'American' aroma which often does not find favour with British drinkers. Strong spicy, blackcurrant or lemon flavour."},
	 'Centennial': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 10.5, 'Use': 'Bittering', 'Description': 'New variety, quite floral qualities similar to Cascade'},
	 'Susan': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 9.0, 'Use': 'Aroma', 'Description': 'Fresh flowers with hints of lemon spices. clean and aromatic.'},
	 'Ahtanum': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 6.0, 'Use': 'Aroma', 'Description': 'Distinctive aromatic with moderate bittering.'},
	 'Equinox': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 15.0, 'Use': 'Aroma', 'Description': 'No Description'},
	 'Spalt Select': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 4.3, 'Use': 'Aroma', 'Description': 'A new lager aroma hop.'},
	 'Golding': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 5.7, 'Use': 'Aroma', 'Description': 'The King of hops. A traditional old-fashioned aroma variety with a smooth, almost sweet, slghtly spicy flavour. The delicate, minty, grassy, slightly floral aroma produces a clean, refreshing, full-bodied flavour. Equally suitable as a copper, late or dry hop.'},
	 'Pacific Gem': {'Form': 'Whole', 'Origin': 'New Zealand', 'Alpha': 15.6, 'Use': 'Bittering', 'Description': 'High alpha copper hop with a with distinctive woody oak and berryfruit flavour.'},
	 'Phoenix': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 11.5, 'Use': 'Bittering', 'Description': 'A new high-bittering copper bred as a replacement for high-alpha coppering hops. Has a poor to almost non-existant aroma, making it unsuitable as a late or aroma hop.'},
	 'Progress': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 6.4, 'Use': 'Aroma', 'Description': 'Slightly sweeter alternative to Fuggle with softer more mellow bitterness. A very pleasant, lemon, citrus aroma.'},
	 'Hallertauer Aroma': {'Form': 'Whole', 'Origin': 'New Zealand', 'Alpha': 9.1, 'Use': 'General Purpose', 'Description': 'A New Zealand hop, bred from Mittlefruh, that has a floral, vanilla flavour, excellent for lighter beers. Not as spicy as Mittlefruh.'},
	 'Liberty': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 4.0, 'Use': 'Aroma', 'Description': 'Light aroma with some similarity to Golding and Mittlefruh but with hint of lemon/ citrus.'},
	 'Whitbread Golding': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 6.4, 'Use': 'Aroma', 'Description': 'Whitbread Goldings Variety. Not really a Golding, but very similar. Not so delicate as Goldings with a more robust aroma.'},
	 'Horizon': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 12.0, 'Use': 'Bittering', 'Description': 'Aromatic with good bittering.'},
	 'Styrian Goldings': {'Form': 'Whole', 'Origin': 'Slovenian', 'Alpha': 4.5, 'Use': 'Aroma', 'Description': 'Not a Golding but a Fuggle grown in Slovenia. Although a Fuggle, being grown in a different area does impart subtly different characteristics. Distinctive perfume with a pine, lemon, citrus hoppy character.'},
	 'Perle': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 8.25, 'Use': 'General Purpose', 'Description': 'A general-purpose hop, similar to Mittlefruh, but with more fruit and higher alpha. Good aroma.'},
	 'First Gold': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 8.3, 'Use': 'General Purpose', 'Description': 'A cross with W.G.V, First Gold provides a well-balanced bitterness with fruity, slightly spicy and orangy, citrus notes. Suitable for copper, late and dry hopping.'},
	 'Hallertauer Hersbrucker': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 2.9, 'Use': 'Aroma', 'Description': 'A lager hop Similar to Mittlefruh with floral slightly fruity flavour'},
	 'Galena': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 12.2, 'Use': 'Aroma', 'Description': 'Excellent high alpha and blackcurrant aroma gives strong fruity character. Similar to Bullion, used in Guinness.'},
	 'Santiam': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 6.0, 'Use': 'Aroma', 'Description': 'Tettnanger type of hop, very similar, with a delicate aroma.'},
	 'Brewers Gold': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 6.1, 'Use': 'Bittering', 'Description': 'A bittering hop that finds application in lagers. Gives a well-balanced bitterness and a fruity spicy character. Not good as an aroma hop.'},
	 'Herald': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 12.7, 'Use': 'Bittering', 'Description': 'A new variety of hop developed as a less harsh alternative to Target, but suitable as a replacement for many high-alpha or general purpose hops. Herald produces a well-rounded gentle grapefruit/ citrus aroma.'},
	 'Chinook': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 11.5, 'Use': 'Aroma', 'Description': 'High alpha with strong grapefruit character and American-style flavour.'},
	 'Cluster': {'Form': 'Whole', 'Origin': 'American', 'Alpha': 7.4, 'Use': 'General Purpose', 'Description': 'Excellent well balanced bittering with deep fruity hop aroma.'},
	 'Jenny': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 9.8, 'Use': 'Aroma', 'Description': 'Aniseed/ liquorice combine in a well balanced hop.'},
	 'Tettnang': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 4.3, 'Use': 'Aroma', 'Description': 'Traditional lager aroma hop.'},
	 'Spalt': {'Form': 'Whole', 'Origin': 'German', 'Alpha': 4.5, 'Use': 'Aroma', 'Description': 'Traditional lager hop with a very fine aroma.'},
	 'Cinnamon': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 0.0, 'Use': 'Aroma', 'Description': 'No Description'},
	 'Elderflowers, dried': {'Form': 'Whole', 'Origin': 'British', 'Alpha': 0.0, 'Use': 'Aroma', 'Description': 'No Description'},
	 'Ginger Root': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 0.0, 'Use': 'Aroma', 'Description': 'No Description'},
	 'Nutmeg': {'Form': 'Whole', 'Origin': 'English', 'Alpha': 0.0, 'Use': 'Aroma', 'Description': 'No Description'}
}

water_chemistry_additions = {
	u'Gypsum': {'Values': {'Type': 'Malt'}}, 					#{'EBC': 0.0, 'Type': 0.0, 'Extract': 0.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 0.0},
	u'Calcium Sulphate': {'Values': {'Type': 'Malt'}}, 			#{'EBC': 0.0, 'Type': 0.0, 'Extract': 0.0, 'Description': 'No Description', 'Moisture': 0.0, 'Fermentability': 0.0},
	u'Irish Moss': {'Values': {'Time': 10, 'Type': 'Hop'}},		# {'Form': 'Whole', 'Origin': 'Unknown', 'Description': 'No Description', 'Use': 'N/A', 'Alpha': 0},
	u'Nutrient': {'Values': {'Time': 10, 'Type': 'Hop'}} 		#{'Form': 'Whole', 'Origin': 'Unknown', 'Description': 'No Description', 'Use': 'N/A', 'Alpha': 0}
}

yeast_data = {'Abbaye Belgian Ale': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '19-22°', 'Description': 'Abbaye is an ale yeast of Belgian origin selected for its ability to produce great Belgian style beers including high gravity beers such as Dubbel, Trippel and Quads.', 'Origin': 'Unknown'},
	 'Abbey Ale WLP530': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '75-80%', 'Temperature': '19-22°', 'Description': ' Produces fruitiness and plum characteristics.', 'Origin': 'Westmalle'},
	 'Abbey IV WLP540': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '19-22°', 'Description': ' Authentic Trappist style yeast. Available Jul-Aug.', 'Origin': 'Rochefort'},
	 'Alt Ale BRY 144': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '15-20°', 'Description': ' Full flavoured, but clean tasting with estery flavour.', 'Origin': 'Unknown'},
	 'Amer. Hefeweizen Ale WLP320': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '70-75%', 'Temperature': '18-21°', 'Description': ' Produces a slight amount of banana and clove notes.', 'Origin': 'Zum Uerige (through Widmer)'},
	 'American Ale 1056': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': '73-77%', 'Temperature': '16-22°', 'Description': ' Well balanced. Ferments dry, finishes soft.', 'Origin': 'Sierra Nevada (Seibel 96)'},
	 'American Ale BRY 96': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '18-22°', 'Description': ' Clean ale strain', 'Origin': 'Unknown'},
	 'American Ale II 1272': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '72-76%', 'Temperature': '16-22°', 'Description': ' Slightly nutty, soft, clean and tart finish.', 'Origin': 'Anchor Liberty'},
	 'American Ale Yeast Blend WLP060': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '72-80%', 'Temperature': '20-22°', 'Description': ' Blend celebrates the strengths of California ale strains.', 'Origin': '(WLP001, WLP051, WLP810?)'},
	 'American Farmhouse Blend WLP670': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '20-22°', 'Description': ' Consists of a traditional farmhouse strain and Brettanomyces.', 'Origin': 'Unknown'},
	 'American Lager 118': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '20-22°', 'Description': ' Produces slightly fruity beer, some residual sugar.', 'Origin': 'Unknown'},
	 'American Lager 2035': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '9-14°', 'Description': ' Bold, complex and aromatic; slight diacetyl.', 'Origin': 'August Schell'},
	 'American Lager WLP840': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '10-13°', 'Description': ' Dry and clean with a very slight apple fruitiness.', 'Origin': 'Budweiser'},
	 'American West Coast Ale BRY-97': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '17-17°', 'Description': ' Very clean ale flavour.', 'Origin': 'Unknown'},
	 'American Wheat 1010': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '74-78%', 'Temperature': '14-23°', 'Description': ' Produces a dry, slightly tart, crisp beer.', 'Origin': 'Widmer vis Zum Uerige'},
	 'American Whiskey WLP065': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '76-82%', 'Temperature': '24-28°', 'Description': ' Produces low ester profile and moderate fussel oils. Used in high-gravity beers.', 'Origin': 'Unknown'},
	 'Antwerp Ale WLP515': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '19-21°', 'Description': ' Clean, almost lager-like with biscuity ale aroma. Available Nov-Dec.', 'Origin': 'De Koninck'},
	 'Australian Ale WLP009': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '70-75%', 'Temperature': '18-21°', 'Description': ' For a clean, malty and bready beer.', 'Origin': 'Coopers'},
	 'Baltic Lager ECY22': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '24-26°', 'Description': ' Full malt flavour and clean finish.', 'Origin': 'Unknown'},
	 'Bastogne Belgian Ale Yeast WLP510': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '74-80%', 'Temperature': '19-22°', 'Description': ' A high gravity, Trappist style ale yeast.', 'Origin': 'Orval'},
	 'Bavarian Lager 2206': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-77%', 'Temperature': '8-14°', 'Description': ' Produces rich, malty, full-bodied beers.', 'Origin': 'Weihenstephan 206'},
	 'Bavarian Weizen Ale WLP351': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '19-21°', 'Description': ' Moderately high, spicy phenolic overtones of cloves.', 'Origin': 'Weihenstephan 175'},
	 'Bavarian Weizen BRY 235': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '10-14°', 'Description': ' A very estery beer with mild clove-like spiciness.', 'Origin': 'Unknown'},
	 'Bavarian Wheat 3638': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '70-76%', 'Temperature': '18-24°', 'Description': ' Balance banana esters w/ apple and plum esters.', 'Origin': 'Weihenstephan 175'},
	 'Bavarian Wheat Blend 3056': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-77%', 'Temperature': '18-23°', 'Description': ' Produces mildly estery and phenolic wheat beers.', 'Origin': 'Unknown'},
	 'Bavarian Wheat Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '15-30°', 'Description': ' Lots of classic banana and clove esters, balanced with clove and cinnamon-like phenolic aromas.', 'Origin': 'Unknown'},
	 'Bedford British Ale WLP006': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '72-80%', 'Temperature': '18-21°', 'Description': ' Good choice for most English style ales.', 'Origin': 'Charles Wells'},
	 'Belgian Abbaye ECY09': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '19-22°', 'Description': ' Limited availability. Robust, estery with large notes of clove and fruit.', 'Origin': 'Unknown'},
	 'Belgian Abbey 1214': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': '74-78%', 'Temperature': '20-26°', 'Description': ' Abbey-style, top-fermenting yeast for high gravity.', 'Origin': 'Chimay'},
	 'Belgian Abbey II 1762': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-77%', 'Temperature': '18-24°', 'Description': ' Slightly fruity with a dry finish.', 'Origin': 'Rochefort'},
	 'Belgian Ale WLP550': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '78-85%', 'Temperature': '20-26°', 'Description': ' Phenolic and spicy flavours dominate the profile.', 'Origin': 'Achouffe'},
	 'Belgian Ale Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '26-32°', 'Description': ' Slight peppery characteristics.', 'Origin': 'Unknown'},
	 'Belgian Ardennes 3522': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '72-76%', 'Temperature': '18-29°', 'Description': ' Mild fruitiness with complex spicy character.', 'Origin': 'Achouffe'},
	 'Belgian Dark Ale 3822-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '18-27°', 'Description': ' Seasonal Availability. High acid producer with balanced ester and phenol production allowing a good expression of malt profile.', 'Origin': 'Unknown'},
	 'Belgian Golden Ale WLP570': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '73-78%', 'Temperature': '20-24°', 'Description': ' A combination of fruitiness and phenolic flavours.', 'Origin': 'Duvel (Moortgart) via McEwans'},
	 'Belgian Lager WLP815': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '10-13°', 'Description': ' Clean, crisp with low sulfur production. Available Jan-Feb.', 'Origin': 'Unknown'},
	 'Belgian Lambic Blend 3278': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': '65-75%', 'Temperature': '17-24°', 'Description': ' Rich, earthy aroma and acidic finish.', 'Origin': 'Unknown'},
	 'Belgian Saison 3724': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '76-80%', 'Temperature': '21-35°', 'Description': ' Very tart and dry with spicy and bubblegum aromatics', 'Origin': 'Saison du Pont'},
	 'Belgian Saison I WLP565': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '65-75%', 'Temperature': '20-24°', 'Description': ' Produces earthy, spicy, and peppery notes.', 'Origin': 'Brasserie Dupont (Saison Dupont)'},
	 'Belgian Saison II WLP566': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '20-26°', 'Description': ' Fruity ester production, moderately phenolic.', 'Origin': 'Vieille Provision Saison Dupont'},
	 'Belgian Saison III WLP585': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': 'Medium', 'Temperature': '20-24°', 'Description': ' High fruit ester, slight tartness. Available Jul-Aug.', 'Origin': 'Unknown'},
	 'Belgian Schelde Ale 3655-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '17-23°', 'Description': ' Seasonal Availability. Produces complex Belgian flavours and aromas.', 'Origin': 'Unknown'},
	 'Belgian Sour Mix WLP655': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '70-80%', 'Temperature': '27-29°', 'Description': ' Includes Brettanomyces, Saccharomyces, and the bacterial strains Lactobacillus and Pedioccus.', 'Origin': 'Unknown'},
	 'Belgian Stout 1581-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '18-24°', 'Description': ' Seasonal Availability. Ferments to dryness and produces moderate levels of esters.', 'Origin': 'Unknown'},
	 'Belgian Strong Ale 1388': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '74-78%', 'Temperature': '18-27°', 'Description': ' Fruity nose and palate, dry, tart finish.', 'Origin': 'Duvel (Moortgart) via McEwans'},
	 'Belgian Strong Ale WLP545': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '19-22°', 'Description': ' Moderate levels of ester and spicy phenolic character.', 'Origin': 'Unknown'},
	 'Belgian Style Ale Yeast Blend WLP575': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '74-80%', 'Temperature': '20-24°', 'Description': ' Blend of Trappist yeast and Belgian ale yeast', 'Origin': 'WLP500, WLP530, WLP550'},
	 'Belgian Style Saison Ale Blend WLP568': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '70-80%', 'Temperature': '21-27°', 'Description': ' Complex, fruity aromas and flavours.', 'Origin': 'Unknown'},
	 'Belgian Wheat 3942': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '72-76%', 'Temperature': '18-23°', 'Description': ' Apple and plum like nose with dry finish.', 'Origin': 'Esen, Belgium (De Dolle)'},
	 'Belgian White ECY11': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '21-24°', 'Description': ' Produces flavours reminiscent of wit biers', 'Origin': 'Unknown'},
	 'Belgian Wit Ale WLP400': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '74-78%', 'Temperature': '19-23°', 'Description': ' Slightly phenolic and tart.', 'Origin': 'Hoegaarden/Celis'},
	 'Belgian Wit II Ale WLP410': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '70-75%', 'Temperature': '19-23°', 'Description': ' Spicier, sweeter, and less phenolic than WLP400.', 'Origin': 'Moortgat Brouwerij (via Ommegang?)'},
	 'Belgian Witbier 3944': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '72-76%', 'Temperature': '16-24°', 'Description': ' Alcohol tolerant, with tart, slight phenolic profile.', 'Origin': 'Hoegaarden/ Celis White'},
	 'Belle Saison': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '17-17°', 'Description': ' Aroma is fruity, spicy and peppery due to ester and phenol production.', 'Origin': 'Unknown'},
	 'Berliner Blend ECY06': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Berliner Weisse Blend WLP630': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '63-80%', 'Temperature': '20-22°', 'Description': ' Creates a subtle tart drinkable beer.', 'Origin': 'Unknown'},
	 'Berliner-Weisse Blend 3191-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '20-22°', 'Description': ' Seasonal availability. Includes a German ale strain and Lactobacillus.', 'Origin': 'Unknown'},
	 'Biere de Garde 3725-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '21-29°', 'Description': ' Seasonal Availability. Low to moderate ester production with subtle spiciness.', 'Origin': 'Unknown'},
	 'Bohemian Lager 2124': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-77%', 'Temperature': '7-20°', 'Description': ' Ferments clean and malty.', 'Origin': 'Weihenstephan 34/70'},
	 'Bohemian Lager Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '10-15°', 'Description': ' Earthy spiciness of both noble hops and Pilsner malt will be enhanced and supported by moderate to full body.', 'Origin': 'Unknown'},
	 'Bourbon Yeast WLP070': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '22-25°', 'Description': ' Produces a caramel malty character with balanced ester profile. Used in high-gravity beers.', 'Origin': 'Unknown'},
	 'Brett Anomala ECY04': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Brett bruxelensis ECY05': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Brett custersianus': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Brett nanus': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Brettan. Bruxellensis 5112': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '16-24°', 'Description': ' Produces classic lambic characteristics.', 'Origin': 'Unknown'},
	 'Brettan. Lambicus 5526': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '16-24°', 'Description': ' Pie cherry-like flavour and sourness.', 'Origin': 'Unknown'},
	 'Brettanomyces Bruxellensis Trois': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '21-29°', 'Description': ' Produces a slightly tart beer with delicate characteristics of mango and pineapple.', 'Origin': 'Unknown'},
	 'Brettanomyces Bruxellensis Trois WLP644': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '85-85%', 'Temperature': '21-29°', 'Description': ' Produces a slightly tart beer with delicate characteristics of mango and pineapple.', 'Origin': 'Unknown'},
	 'Brettanomyces bruxellensis WLP650': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '70-85%', 'Temperature': '29-29°', 'Description': ' Classic strain used in secondary for Belgian styles.', 'Origin': 'Unknown'},
	 'Brettanomyces Claussenii WLP645': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '70-85%', 'Temperature': '29-29°', 'Description': ' Low intensity Brett character. More aroma than flavour.', 'Origin': 'Unknown'},
	 'Brettanomyces Lambicus WLP653': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '70-85%', 'Temperature': '29-29°', 'Description': ' High Brett character. Horsey, Smokey and spicy flavours.', 'Origin': 'Unknown'},
	 'Brewferm Blanche': {'Type': 'D', 'Lab': 'Brewferm', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '18-23°', 'Description': ' Ferments clean with little or no sulphur.', 'Origin': 'Unknown'},
	 'Brewferm Lager': {'Type': 'D', 'Lab': 'Brewferm', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '10-15°', 'Description': ' Develops Witbeer aromas like banana and clove.', 'Origin': 'Unknown'},
	 'Brewferm Top': {'Type': 'D', 'Lab': 'Brewferm', 'Flocculation': 'Med/High', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'No Description', 'Origin': 'Unknown'},
	 'British Ale 1098': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-75%', 'Temperature': '18-22°', 'Description': ' Ferments dry and crisp, slightly tart and fruity.', 'Origin': 'Whitbread - dry'},
	 'British Ale II 1335': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '73-75%', 'Temperature': '17-24°', 'Description': ' Malty flavour, crisp finish, clean, fairly dry.', 'Origin': 'Unknown'},
	 'British Ale WLP005': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '75-80%', 'Temperature': '20-24°', 'Description': ' English strain that produces malty beers.', 'Origin': 'Ringwood'},
	 'British Ale Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '14-22°', 'Description': ' Earthy, nutty, orange peel and mild spice.', 'Origin': 'Unknown'},
	 'British Cask Ale 1026-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Med/High', 'Attenuation': 'Medium', 'Temperature': '17-22°', 'Description': ' Seasonal Availability. Produces a nice malt profile and finishes crisp and slightly tart.', 'Origin': 'Unknown'},
	 'British Mild Ale ECY18': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Low', 'Attenuation': 'Low', 'Temperature': '16-20°', 'Description': ' Limited availability. Complex, woody ester profile. Leaves a malt profile with a slight sweetness.', 'Origin': 'Unknown'},
	 'Budvar Lager 2000': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Med/High', 'Attenuation': '71-75%', 'Temperature': '9-13°', 'Description': ' Malty nose with subtle fruit. Finishes dry and crisp.', 'Origin': 'Budvar'},
	 'BugCounty ECY20': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'BugFarm ECY01': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Burton Ale WLP023': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '69-75%', 'Temperature': '20-23°', 'Description': ' Subtle fruity flavours: apple, clover honey and pear.', 'Origin': 'Henley of Thames (Brakspear Bitter)'},
	 'Burton Union ECY17': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '18-21°', 'Description': ' Limited availability. Citrusy flavour which accentuates mineral and hop flavours.', 'Origin': 'Unknown'},
	 'Burton Union Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '17-23°', 'Description': ' Some pear esters, possibly strawberry or kiwi-like aromas.', 'Origin': 'Unknown'},
	 'California Ale V WLP051': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '70-75%', 'Temperature': '19-21°', 'Description': ' Produces a fruity, full-bodied beer.', 'Origin': 'Anchor Liberty'},
	 'California Ale WLP001': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '73-80%', 'Temperature': '20-23°', 'Description': ' Clean flavours accentuate hops; very versatile.', 'Origin': 'Sierra Nevada'},
	 'California Lager 2112': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '67-71%', 'Temperature': '14-20°', 'Description': ' Produces malty, brilliantly clear beers.', 'Origin': 'Anchor'},
	 'Canadian/Belgian Ale 3864-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '18-27°', 'Description': ' Seasonal Availability. Banana and fruit esters complemented with mild phenolics and hints of acidity.', 'Origin': 'Unknown'},
	 'CBC-1 (Cask and Bottle Conditioning)': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Low/Med', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'No Description', 'Origin': 'Unknown'},
	 'Coopers Pure Brewers\' Yeast': {'Type': 'D', 'Lab': 'Coopers', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '20-27°', 'Description': ' Clean, round flavour profile.', 'Origin': 'Unknown'},
	 'Cream Ale WLP80': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '18-21°', 'Description': ' A blend of ale and lager strains that creates a clean, crisp, light American lager style.', 'Origin': 'Unknown'},
	 'Cry Havoc WLP862': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': 'Low', 'Temperature': '13-14°', 'Description': ' Can ferment at ale and lager temperatures, allowing for a variety of beer styles.', 'Origin': 'Unknown'},
	 'Czech Budejovice Lager WLP802': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '10-13°', 'Description': ' Produces dry and crisp lagers, with low diacetyl.', 'Origin': 'Samsons via Budejovicky Mestansky Pivovar'},
	 'Czech Pils 2278': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '70-74%', 'Temperature': '10-14°', 'Description': ' Dry but malty finish.', 'Origin': 'Pilsner Urquell-D'},
	 'Danish Lager 2042': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '8-13°', 'Description': ' Rich Dortmund style with crisp, dry finish.', 'Origin': 'Miller via Carlsberg'},
	 'Denny\'s Favorite 50 1450': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '16-21°', 'Description': ' Can be used for almost any beer style. Accentuates malt, caramel, or fruit character.', 'Origin': 'Unknown'},
	 'Dry English ale WLP007': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '70-80%', 'Temperature': '18-21°', 'Description': ' Good for high gravity ales with no residuals.', 'Origin': 'Whitbread - dry'},
	 'Dusseldorf Alt WLP036': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '65-72%', 'Temperature': '18-21°', 'Description': ' Produces clean, slightly sweet alt beers.', 'Origin': 'D�sseldorf (Zum Uerige)'},
	 'East Coast Ale WLP008': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '70-75%', 'Temperature': '20-23°', 'Description': ' Very clean and low esters.', 'Origin': u"Sam Adam's"},
	 'East Midlands Ale WLP039': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': 'Medium', 'Temperature': '19-21°', 'Description': ' Available Sept-Oct. Medium to low fusel fruit and alcohol production.', 'Origin': 'UK, chosen from multistrain - same as Danstar Nottingham'},
	 'Edinburgh Ale WLP028': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '70-75%', 'Temperature': '18-21°', 'Description': ' Malty, strong Scottish ales.', 'Origin': u"McEwan's"},
	 'English Ale Blend WLP085': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '69-76%', 'Temperature': '20-22°', 'Description': ' Moderate fruitiness and mineral-like.', 'Origin': 'Unknown'},
	 'English Ale BRY 264': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '15-20°', 'Description': ' Clean ale with slightly nutty and estery character.', 'Origin': 'Unknown'},
	 'English Ale WLP002': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Very High', 'Attenuation': '63-70%', 'Temperature': '18-20°', 'Description': ' Very clear with some residual sweetness.', 'Origin': 'Fullers'},
	 'English Special Bitter 1768-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Low', 'Temperature': '18-22°', 'Description': ' Seasonal Availability. Produces light fruit and ethanol aromas along with soft, nutty flavours.', 'Origin': 'Unknown'},
	 'Essex Ale Yeast WLP022': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '71-76%', 'Temperature': '19-21°', 'Description': ' Drier finish than many British ale yeasts', 'Origin': u"Ridley's Ale near Chelmsford, UK"},
	 'European Ale WLP011': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '65-70%', 'Temperature': '18-21°', 'Description': ' Low ester production, giving a clean profile.', 'Origin': 'Wisenschaftliche Station #338 (Munich)'},
	 'European Lager 2247-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '8-13°', 'Description': ' Seasonal Availability. Exhibits a clean and dry flavour profile often found in aggressively hopped lagers.', 'Origin': 'Unknown'},
	 'Farmhouse Ale 3726-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '21-29°', 'Description': ' Seasonal Availability. Complex esters balanced with earthy/spicy notes.', 'Origin': 'Unknown'},
	 'Farmhouse Brett ECY03': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Fermentis US-05': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Medium', 'Attenuation': '77-81%', 'Temperature': '15-24°', 'Description': ' Clean with mild flavour for a wide range of styles.', 'Origin': 'Unknown'},
	 'Flanders Golden Ale 3739-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': 'Medium', 'Temperature': '18-27°', 'Description': ' Seasonal Availability. Will produce moderate fruity esters and spicy phenols.', 'Origin': 'Unknown'},
	 'Flemish Ale Blend WLP665': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': 'High', 'Temperature': '20-27°', 'Description': ' Creates a complex, dark stone fruit characteristic.', 'Origin': 'Unknown'},
	 'Flemish Ale ECY02': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Forbidden Fruit Yeast 3463': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '17-24°', 'Description': ' Phenolic profile, subdued fruitiness.', 'Origin': 'Hoegaarden (assumed to be from Verboden Vrucht)'},
	 'Frankenyeast': {'Type': 'L', 'Lab': 'Various', 'Flocculation': 'Low', 'Attenuation': '75%', 'Temperature': '16-24°', 'Description': 'A blend of twenty-five yeast strains, most of which are English or Belgian in origin.', 'Origin': 'Unknown'},
	 'French Ale WLP072': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': 'Low', 'Temperature': '17-23°', 'Description': ' Clean strain that complements malt flavour. Available May-June.', 'Origin': 'Unknown'},
	 'French Saison 3711': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '18-25°', 'Description': ' Versatile strain for Saisons and other Belgian styles that are aromatic, estery, and spicy.', 'Origin': 'Brasserie Thiriez'},
	 'German Ale 1007': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '13-20°', 'Description': ' Ferments dry and crisp with a mild flavour.', 'Origin': 'D�sseldorf (Zum Uerige)'},
	 'German Ale/Kölsch WLP029': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '72-78%', 'Temperature': '18-21°', 'Description': ' A super-clean, lager-like ale.', 'Origin': 'PJ Fr�h, K�ln'},
	 'German Bock Lager Yeast WLP833': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '70-76%', 'Temperature': '9-13°', 'Description': ' Produces well balanced beers of malt and hop character.', 'Origin': 'Ayinger Brewery'},
	 'German Lager WLP830': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '74-79%', 'Temperature': '10-13°', 'Description': ' Malty and clean; great for all German lagers.', 'Origin': 'Weihenstephan 34/70'},
	 'German Wheat 3333': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '73-77%', 'Temperature': '17-24°', 'Description': ' Sharp, tart crispness, fruity, sherry-like palate.', 'Origin': 'Unknown'},
	 'Hefeweizen Ale WLP300': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '72-76%', 'Temperature': '20-22°', 'Description': ' Produces banana and clove nose.', 'Origin': 'Weihenstephan 68'},
	 'Hefeweizen IV Ale WLP380': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low', 'Attenuation': '73-80%', 'Temperature': '19-21°', 'Description': ' Crisp, large clove and phenolic aroma and flavour.', 'Origin': 'Weihenstephan 66?'},
	 'Hella Bock 2487-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '9-13°', 'Description': ' Seasonal Availability. Attenuates well while still leaving plenty of malt character and body.', 'Origin': 'Unknown'},
	 'Irish Ale 1084': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '71-75%', 'Temperature': '17-22°', 'Description': ' Slight residual diacetyl and fruitiness.', 'Origin': 'Guinness'},
	 'Irish Ale WLP004': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '69-74%', 'Temperature': '18-20°', 'Description': ' Light fruitiness and slight dry crispness.', 'Origin': 'Guinness'},
	 'Kölsch 2565': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '13-21°', 'Description': ' Malty with a subdued fruitiness and a crisp finish.', 'Origin': 'Weihenstephan 165, K�ln (P�ffgen?)'},
	 'Kolsch II 2575-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '13-21°', 'Description': ' Seasonal Availability. Rich flavour profile which accentuates a soft malt finish.', 'Origin': 'Unknown'},
	 'Kölschbier ECY21': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '14-19°', 'Description': ' Limited availability. Clean lager-like profile at ale temperatures.', 'Origin': 'Unknown'},
	 'Lactobacillus 5335': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Leuven Pale Ale 3538-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '18-27°', 'Description': ' Seasonal Availability. Produces a spicy character and mild esters.', 'Origin': 'Unknown'},
	 'London Ale 1028': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': '73-77%', 'Temperature': '16-22°', 'Description': ' Bold and crisp with a rich mineral profile.', 'Origin': 'Worthington White Shield'},
	 'London Ale III 1318': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '71-75%', 'Temperature': '18-23°', 'Description': ' Very light and fruity, with a soft, balanced palate.', 'Origin': 'Boddingtons'},
	 'London Ale WLP013': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '67-75%', 'Temperature': '19-22°', 'Description': ' Dry malty ale yeast for pales, bitters and stouts.', 'Origin': 'Worthington White Shield'},
	 'London ESB Ale 1968': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '67-71%', 'Temperature': '18-22°', 'Description': ' Rich, malty character with balanced fruitiness.', 'Origin': 'Fullers'},
	 'Lucky #7': {'Type': 'L', 'Lab': 'Real Brewers Yeast', 'Flocculation': 'High', 'Attenuation': '70-80%', 'Temperature': '20-24°', 'Description': ' Southern California ale yeast that ferments higher gravity worts up to 10% ABV.', 'Origin': 'Unknown'},
	 'Manchester Ale WLP038': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': 'Medium', 'Temperature': '18-21°', 'Description': ' Clean, dry finish with low esters.', 'Origin': 'Unknown'},
	 'Mexican Lager Yeast WLP940': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '70-78%', 'Temperature': '10-13°', 'Description': ' Produces clean lager beer, with a crisp finish.', 'Origin': 'Grupo Modelo'},
	 'Munich (German Wheat Beer)': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Very Low', 'Attenuation': 'Medium', 'Temperature': '17-17°', 'Description': ' Estery to both palate and nose with typical banana notes.', 'Origin': 'Unknown'},
	 'Munich Festbier ECY15': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '8-12°', 'Description': ' Recommended for German lagers', 'Origin': 'Unknown'},
	 'Munich Helles WLP860': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '9-11°', 'Description': ' Clean and strong fermenter. Available Mar-Apr.', 'Origin': 'Unknown'},
	 'Munich Lager 2308': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '70-74%', 'Temperature': '9-13°', 'Description': ' Very smooth, well-rounded and full-bodied.', 'Origin': 'Wisenschaftliche Station #308 (Munich)'},
	 'Munich Lager II 2352-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '11-17°', 'Description': ' Seasonal Availability. Low diacetyl and low sulfur aroma. Great for malt-driven lagers.', 'Origin': 'Unknown'},
	 'Muntons Premium Gold': {'Type': 'D', 'Lab': 'Muntons', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '14-25°', 'Description': ' Clean balanced ale yeast for 100% malt recipies.', 'Origin': 'Unknown'},
	 'Muntons Standard Yeast': {'Type': 'D', 'Lab': 'Muntons', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '14-25°', 'Description': ' Clean well balanced ale yeast.', 'Origin': 'Unknown'},
	 'Neutral Grain WLP078': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '77-84%', 'Temperature': '24-29°', 'Description': ' Clean, fast fermentation used in high-gravity beers.', 'Origin': 'Unknown'},
	 'Newcastle Dark Ale Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '18-22°', 'Description': ' Aromas reminiscent of rich, dark fruit.', 'Origin': 'Unknown'},
	 'North American Lager 2272-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '11-14°', 'Description': ' Seasonal Availability. Mild malty profile, medium ester profile, well balanced.', 'Origin': 'Unknown'},
	 'North European Lager BRY 203': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'Low', 'Attenuation': 'High', 'Temperature': '20-22°', 'Description': ' Well-balanced beer, fewer sulfur compounds.', 'Origin': 'Unknown'},
	 'Northeast Ale ECY29': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '18-21°', 'Description': ' A unique ale yeast with an abundance of citrusy esters accentuating American style hops.', 'Origin': 'Unknown'},
	 'Northwest Ale 1332': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '67-71%', 'Temperature': '18-24°', 'Description': ' Malty, mildly fruity, good depth and complexity.', 'Origin': 'Hales Brewery in Seattle via Gales Brewery UK'},
	 'Nottingham': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '14-21°', 'Description': ' Neutral for an ale yeast; fruity estery aromas.', 'Origin': 'Unknown'},
	 'Octoberfest Lager Blend 2633': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low/Med', 'Attenuation': '73-77%', 'Temperature': '9-14°', 'Description': ' Plenty of malt character and mouth feel. Low in sulfur.', 'Origin': 'Unknown'},
	 'Oktoberfest/Märzen WLP820': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '65-73%', 'Temperature': '11-14°', 'Description': ' Produces a very malty, bock-like style.', 'Origin': 'Weihenstephan 206'},
	 'Old Bavarian Lager Yeast WLP920': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '66-73%', 'Temperature': '10-13°', 'Description': ' Finishes malty with a slight ester profile. Use in beers such as Octoberfest, Bock, and dark lagers.', 'Origin': 'Unknown'},
	 'Old Newark Ale ECY10': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'High', 'Attenuation': 'Low', 'Temperature': '16-20°', 'Description': ' Good for all styles of American and English ales', 'Origin': 'Unknown'},
	 'Old Newark Beer ECY12': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '14-20°', 'Description': ' Identified as S. cerevisae, hence it is not a true lager strain, but should ferment at lager temperatures.', 'Origin': 'Unknown'},
	 'Old Sonoma Ale WLP076': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '19-21°', 'Description': ' Neutral and versatile. Available May-June', 'Origin': 'Unknown'},
	 'Oud Brune ECY23': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'No Description', 'Origin': 'Unknown'},
	 'Pacific Ale WLP041': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '65-70%', 'Temperature': '18-20°', 'Description': ' A popular ale yeast from the Pacific Northwest.', 'Origin': '(Red Hook?)'},
	 'Pediococcus Cerivisiae 5733': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'Unknown', 'Origin': 'Unknown'},
	 'Pilsen Lager 2007': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '71-75%', 'Temperature': '9-13°', 'Description': ' Smooth malty palate; ferments dry and crisp.', 'Origin': 'Budweiser'},
	 'Pilsner Lager WLP800': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '72-77%', 'Temperature': '10-13°', 'Description': ' Somewhat dry with a malty finish.', 'Origin': 'Pilsner Urquell'},
	 'Rasenmäher Lager 2252-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '9-20°', 'Description': ' Seasonal Availability. Produces clean lagers at low temp. fermentations, but also yields slight ester at higher temps.', 'Origin': 'Unknown'},
	 'Ringwood Ale 1187': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '68-72%', 'Temperature': '18-23°', 'Description': ' A malty, complex profile that clears well.', 'Origin': 'Pripps Brewery, Sweden (aka 1742 Swedish porter)'},
	 'Rocky Mountain Lager 2105-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Med/High', 'Attenuation': 'Medium', 'Temperature': '9-13°', 'Description': ' Seasonal Availability. Mild malty profile, medium esters, well balanced.', 'Origin': 'Unknown'},
	 'Roeselare Ale Blend 3763': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'No Description', 'Origin': 'Rodenbach'},
	 'SafAle BE-134': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Unknown', 'Attenuation': 'Unknown', 'Temperature': 'Unknown', 'Description': 'No Description', 'Origin': 'Unknown'},
	 'SafAle S-04': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'High', 'Attenuation': '79-79%', 'Temperature': '15-24°', 'Description': ' English ale yeast that forms very compact sediment.', 'Origin': 'Unknown'},
	 'SafAle US-05': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '15-22°', 'Description': ' Produces well-balanced beers with low diacetyl and clean end palate.', 'Origin': 'Unknown'},
	 'Safbrew S-33': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Med/High', 'Attenuation': '75-75%', 'Temperature': '15-24°', 'Description': ' Versatile strain that can perform in beers up to 11.5% ABV.', 'Origin': 'Unknown'},
	 'Safbrew T-58': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Low', 'Attenuation': '75-75%', 'Temperature': '15-24°', 'Description': ' Develops estery and somewhat peppery spiceyness.', 'Origin': 'Unknown'},
	 'Safbrew WB-06': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '18-24°', 'Description': ' Produces subtle estery and phenol flavour notes typical of wheat beers.', 'Origin': 'Unknown'},
	 'SafLager S-23': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'Med/High', 'Attenuation': '80-80%', 'Temperature': '9-15°', 'Description': ' Produces a fruit esterness in lagers.', 'Origin': 'Unknown'},
	 'SafLager W-34/70': {'Type': 'D', 'Lab': 'Fermentis', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '12-15°', 'Description': ' Good balance of floral and fruity aromas, clean flavour.', 'Origin': 'Unknown'},
	 'Saison Brasserie Blend ECY08': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '24-29°', 'Description': ' Limited availability. Both fruity and spicy characteristics accompanied by dryness.', 'Origin': 'Unknown'},
	 'Saison Single-Strain ECY14': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '24-28°', 'Description': ' Spring/Summer. Smooth, full character with mild esters reminiscent of apple pie spice.', 'Origin': 'Unknown'},
	 'San Diego Super Yeast WLP090': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': 'High', 'Temperature': '18-20°', 'Description': ' Versatile, super-fast, super-clean strain.', 'Origin': 'Unknown'},
	 'San Francisco Lager WLP810': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '65-70%', 'Temperature': '14-18°', 'Description': ' For “California Common” type beer.', 'Origin': 'Anchor Steam'},
	 'Scotch Whiskey WLP045': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '22-25°', 'Description': ' Used for scotch whiskey production from the early 1950s. Used in high-gravity beers.', 'Origin': 'Unknown'},
	 'Scottish Ale 1728': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '69-73%', 'Temperature': '13-24°', 'Description': ' Suited for Scottish-style ales, high-gravity ales.', 'Origin': 'McEwans'},
	 'Scottish Heavy ECY07': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '16-20°', 'Description': ' Limited availability. Leaves a fruity profile with woody, oak esters reminiscent of malt whiskey.', 'Origin': 'Unknown'},
	 'So. German Lager WLP838': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Med/High', 'Attenuation': '68-76%', 'Temperature': '10-13°', 'Description': ' A malty finish and balanced aroma.', 'Origin': 'Unknown'},
	 'Staro Prague Lager 2782-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '10-14°', 'Description': ' Seasonal Availability. Will create moderate fruit and bready malt flavours in lagers.', 'Origin': 'Unknown'},
	 'Super High Gravity WLP099': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '80-%', 'Temperature': '18-21°', 'Description': ' High gravity yeast, ferments up to 25% alcohol.', 'Origin': 'Thomas Hardy'},
	 'Tennessee WLP050': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '24-26°', 'Description': ' Creates rich, smooth flavours. Used in high-gravity beers.', 'Origin': 'Unknown'},
	 'Thames Valley Ale 1275': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '72-76%', 'Temperature': '17-22°', 'Description': ' Clean, light malt character with low esters.', 'Origin': 'Henley of Thames (Brakspear Bitter)'},
	 'Thames Valley Ale II 1882-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Medium', 'Temperature': '16-21°', 'Description': ' Seasonal Availability. Produces crisp, dry beers with rich malt profile and moderate stone fruit esters.', 'Origin': 'Unknown'},
	 'The Monk': {'Type': 'D', 'Lab': 'Real Brewers Yeast', 'Flocculation': 'Medium', 'Attenuation': '75-80%', 'Temperature': '19-22°', 'Description': ' Ferments tripels and high-gravity ales to 15% ABV.', 'Origin': 'Unknown'},
	 'The One': {'Type': 'D', 'Lab': 'Real Brewers Yeast', 'Flocculation': 'High', 'Attenuation': '70-80%', 'Temperature': '20-24°', 'Description': ' California ale yeast great for West Coast-style pale ales and IPAs.', 'Origin': 'Unknown'},
	 'Trappist Ale BRY 204': {'Type': 'L', 'Lab': 'Siebel Inst.', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '18-22°', 'Description': ' Dry estery flavour with a light clove-like spiciness.', 'Origin': 'Unknown'},
	 'Trappist Ale ECY13': {'Type': 'L', 'Lab': 'East Coast Yeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '23-24°', 'Description': ' Traditional Trappist yeast with a complex, dry, fruity malt profile.', 'Origin': 'Unknown'},
	 'Trappist Ale WLP500': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Low/Med', 'Attenuation': '75-80%', 'Temperature': '18-22°', 'Description': ' Distinctive fruitiness and plum characteristics.', 'Origin': 'Chimay'},
	 'Trappist Blend 3789-PC': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': 'Medium', 'Temperature': '20-29°', 'Description': ' Seasonal Availability. A unique blend of Belgian Saccharomyces and Brettanomyces.', 'Origin': 'Unknown'},
	 'Trappist High Gravity 3787': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '74-78%', 'Temperature': '18-26°', 'Description': ' Ferments dry, rich ester profile and malty palate.', 'Origin': 'Westmalle'},
	 'Urquell Lager 2001': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Med/High', 'Attenuation': '72-76%', 'Temperature': '9-13°', 'Description': ' Mild fruit and floral aroma. Very dry with mouth feel.', 'Origin': 'Pilsner Urquell lager H-strain'},
	 'US West Coast Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '15-23°', 'Description': ' Very neutral strain. Citrus and pine hops will be enhanced.', 'Origin': 'Unknown'},
	 'Weihenstephan Weizen 3068': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Low', 'Attenuation': '73-77%', 'Temperature': '18-24°', 'Description': ' A unique, rich and spicy weizen character.', 'Origin': 'Weihenstephan 68 (S. delbrueckii single strain)'},
	 'West Yorkshire Ale 1469': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Low', 'Temperature': '18-22°', 'Description': ' Produces full chewy malt flavour and character. Expect moderate nutty and stone-fruit esters.', 'Origin': 'Timothy Taylor'},
	 'Whitbread Ale 1099': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '68-72%', 'Temperature': '18-23°', 'Description': ' Mildly malty and slightly fruity.', 'Origin': 'Whitbread'},
	 'Whitbread Ale WLP017': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '67-73%', 'Temperature': '19-21°', 'Description': ' Brittish style, slightly fruity with a hint of sulfur.', 'Origin': 'Unknown'},
	 'Windsor (British Ale)': {'Type': 'D', 'Lab': 'Lallemand', 'Flocculation': 'Low', 'Attenuation': 'Medium', 'Temperature': '15-22°', 'Description': ' Full-bodied, fruity English ale.', 'Origin': 'Unknown'},
	 'Workhorse Beer Yeast': {'Type': 'D', 'Lab': 'Mangrove Jack', 'Flocculation': 'Medium', 'Attenuation': 'High', 'Temperature': '15-20°', 'Description': ' Neutral and clean aroma suitable for all styles. Imitates lager characteristics.', 'Origin': 'Unknown'},
	 'Ye Olde English': {'Type': 'D', 'Lab': 'Real Brewers Yeast', 'Flocculation': 'Medium', 'Attenuation': '65-75%', 'Temperature': '18-21°', 'Description': ' Smooth and creamy for English ales.', 'Origin': 'Unknown'},
	 'Yorkshire Square WLP037': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': 'Low', 'Temperature': '18-21°', 'Description': ' Availability: Nov-Dec. Toasty with malt-driven esters.', 'Origin': 'Unknown'},
	 'Zurich Lager Yeast WLP885': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '70-80%', 'Temperature': '10-13°', 'Description': ' Swiss style lager yeast with minimal sulfur and diacetyl production.', 'Origin': 'Samichlaus'},
	 'Brakspear\'s 1275': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '72-76%', 'Temperature': '17-22°', 'Description': ' Clean, light malt character with low esters.', 'Origin': 'Henley of Thames (Brakspear Bitter)'},
	 'Brakspear\'s WLP023': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Medium', 'Attenuation': '69-75%', 'Temperature': '20-23°', 'Description': ' Subtle fruity flavors: apple, clover honey and pear.', 'Origin': 'Henley of Thames (Brakspear Bitter)'},
	 'Charles Wells WLP006': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'High', 'Attenuation': '72-80%', 'Temperature': '18-21°', 'Description': ' Good choice for most English style ales.', 'Origin': 'Charles Wells'},
	 'Fuller\'s 1968': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': '67-71%', 'Temperature': '18-22°', 'Description': ' Rich, malty character with balanced fruitiness.', 'Origin': 'Fullers'},
	 'Fuller\'s WLP002': {'Type': 'L', 'Lab': 'White Labs', 'Flocculation': 'Very High', 'Attenuation': '63-70%', 'Temperature': '18-20°', 'Description': ' Very clear with some residual sweetness.', 'Origin': 'Fullers'},
	 'Gervin English Ale': {'Type': 'D', 'Lab': 'Gervin', 'Flocculation': 'High', 'Attenuation': 'High', 'Temperature': '14-21°', 'Description': ' Neutral for an ale yeast; fruity estery aromas.', 'Origin': 'Unknown'},
	 'Timothy Taylor 1469': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'High', 'Attenuation': 'Low', 'Temperature': '18-22°', 'Description': ' Produces full chewy malt flavour and character. Expect moderate nutty and stone-fruit esters.', 'Origin': 'Timothy Taylor'},
	 'Whitbread Ale (Dry) 1098': {'Type': 'L', 'Lab': 'Wyeast', 'Flocculation': 'Medium', 'Attenuation': '73-75%', 'Temperature': '18-22°', 'Description': ' Ferments dry and crisp, slightly tart and fruity.', 'Origin': 'Whitbread - dry'}
}


constants = {
	u'Efficiency': 0.75,
	u'Hop Time': 60,
	u'Conversion': {'lb-g': 453.592, 'oz-g': 28.35, 'usg-l': 3.785411784},
	u'Volume': 10,
	u'Boil Volume Scale': 1.1,
	u'Liquor To Grist Ratio': 2.5,
	u'Attenuation Default': 'med-66',
	u'Save On Close': True,
	u'Default Boil Time': 90,
	u'Replace Defaults': False
}
